apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-zhhg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-zhhg
    app.kubernetes.io/part-of: test-app-690
  name: pip-e2e-test-zhhg
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-zhhg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-zhhg
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-690/pip-e2e-test-zhhg@sha256:82c6a714148f288d0ec41fb652529fa28dd500c19fb443eebc2796451edcdea0
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
