apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-bovv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-bovv
    app.kubernetes.io/part-of: test-app-690
  name: maven-hello-world-bovv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-bovv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-bovv
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-690/maven-hello-world-bovv@sha256:b10eaf971bc4334e9d59eaae0f0a778e1d3314bf170c356dc20642f0325ee7af
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
