apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-c6ss
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-c6ss
    app.kubernetes.io/part-of: test-app-690
  name: retrodep-c6ss
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-c6ss
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-c6ss
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-690/retrodep-c6ss@sha256:dcdb018d2d20d0d313028a3999016a864997960a51201a49ebc4e12741f89695
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
