apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-yi7f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-yi7f
    app.kubernetes.io/part-of: test-app-690
  name: devfile-sample-python-basic-yi7f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-yi7f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-yi7f
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-690/devfile-sample-python-basic-yi7f@sha256:d459e988906ba8605f508ad967ea43f6645391c660605bf18490014f7a7f51b3
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
